#!/usr/bin/env bash
# =============================================================================
# remote/odoo-harden.sh  -  runs ON the AWS box (as root), driven by
# /etc/odoo-harden.env uploaded by 04-harden-and-tune.sh.
#
# Nginx + TLS, Odoo/PostgreSQL tuning, firewall, fail2ban, auto-updates,
# SSH hardening, CloudWatch (prod), nightly backups. Idempotent.
# =============================================================================
set -Eeuo pipefail
export DEBIAN_FRONTEND=noninteractive

[[ -f /etc/odoo-harden.env ]] || { echo "missing /etc/odoo-harden.env"; exit 1; }
# shellcheck disable=SC1091
source /etc/odoo-harden.env
log(){ echo "[harden] $*"; }

CPUS="$(nproc)"
RAM_MB="$(awk '/MemTotal/{printf "%d", $2/1024}' /proc/meminfo)"
log "Box: ${INSTANCE_TYPE}  cpus=${CPUS}  ram=${RAM_MB}MB  env=${ODOO_ENV}"

# -----------------------------------------------------------------------------
# 1. Odoo worker + limit tuning (sized to CPU/RAM)
# -----------------------------------------------------------------------------
# Odoo guidance: workers = (cpus * 2) + 1, capped by RAM (~1 worker / ~1GB).
WORKERS=$(( CPUS * 2 + 1 ))
RAM_CAP=$(( RAM_MB / 1024 ))
(( WORKERS > RAM_CAP )) && WORKERS=${RAM_CAP}
(( WORKERS < 2 ))       && WORKERS=2
CRON_THREADS=1; (( CPUS >= 4 )) && CRON_THREADS=2
# per-worker memory limits (bytes): soft ~640MB, hard ~768MB
LIM_SOFT=$(( 640 * 1024 * 1024 ))
LIM_HARD=$(( 768 * 1024 * 1024 ))

log "Tuning odoo.conf: workers=${WORKERS}, cron_threads=${CRON_THREADS}, dbfilter=^${TARGET_DBNAME}$"
set_conf(){ # key value
  if grep -qE "^\s*$1\s*=" "${ODOO_CONF}"; then
    sed -i "s|^\s*$1\s*=.*|$1 = $2|" "${ODOO_CONF}"
  else
    echo "$1 = $2" >> "${ODOO_CONF}"
  fi
}
set_conf workers "${WORKERS}"
set_conf max_cron_threads "${CRON_THREADS}"
set_conf limit_memory_soft "${LIM_SOFT}"
set_conf limit_memory_hard "${LIM_HARD}"
set_conf limit_time_cpu 600
set_conf limit_time_real 1200
set_conf limit_request 8192
set_conf proxy_mode "True"
set_conf list_db "False"                       # hide DB manager / no cross-db listing
set_conf dbfilter "^${TARGET_DBNAME}\$"        # serve only this database
set_conf db_maxconn 64
systemctl restart odoo || true

# -----------------------------------------------------------------------------
# 2. PostgreSQL memory tuning (sized to box RAM)
# -----------------------------------------------------------------------------
PG_CONF_D="/etc/postgresql/${PG_VERSION}/main/conf.d"
if [[ -d "$(dirname "${PG_CONF_D}")" ]]; then
  mkdir -p "${PG_CONF_D}"
  SHARED_BUFFERS=$(( RAM_MB / 4 ))                 # 25% RAM
  EFFECTIVE_CACHE=$(( RAM_MB * 3 / 4 ))            # 75% RAM
  MAINT_WORK=$(( RAM_MB / 16 )); (( MAINT_WORK > 1024 )) && MAINT_WORK=1024
  cat > "${PG_CONF_D}/99-odoo-tuning.conf" <<EOF
# generated by odoo-harden.sh for ${INSTANCE_TYPE} (${RAM_MB}MB RAM)
shared_buffers = ${SHARED_BUFFERS}MB
effective_cache_size = ${EFFECTIVE_CACHE}MB
maintenance_work_mem = ${MAINT_WORK}MB
work_mem = 16MB
max_connections = 100
random_page_cost = 1.1
effective_io_concurrency = 200
wal_compression = on
EOF
  log "PostgreSQL tuned (shared_buffers=${SHARED_BUFFERS}MB)"
  systemctl restart postgresql || true
fi

# -----------------------------------------------------------------------------
# 3. Nginx reverse proxy + TLS
# -----------------------------------------------------------------------------
log "Installing nginx + certbot"
TLS_MODE="${TLS_MODE:-letsencrypt}"
apt-get -o DPkg::Lock::Timeout=300 update -qq
apt-get -o DPkg::Lock::Timeout=300 install -y -qq nginx >/dev/null
if [[ "${TLS_MODE}" == "letsencrypt" ]]; then
  apt-get -o DPkg::Lock::Timeout=300 install -y -qq certbot python3-certbot-nginx >/dev/null
fi

# Behind Cloudflare: restore real client IPs from CF-Connecting-IP so Odoo and
# access logs record the visitor, not Cloudflare's edge nodes.
if [[ "${TLS_MODE}" == "cloudflare_origin" ]]; then
  cat > /etc/nginx/conf.d/cloudflare-realip.conf <<'EOF'
# Cloudflare IP ranges - https://www.cloudflare.com/ips/ (refresh if they change)
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;
real_ip_header CF-Connecting-IP;
EOF
fi

# base http block tweaks (upload size etc.) - separate file to avoid clobbering
cat > /etc/nginx/conf.d/odoo-upload.conf <<'EOF'
client_max_body_size 200m;
proxy_read_timeout 720s;
proxy_connect_timeout 720s;
proxy_send_timeout 720s;
EOF

# site: proxies to Odoo (8069) + websocket (8072), gzip, security headers
cat > /etc/nginx/sites-available/odoo.conf <<EOF
upstream odoo      { server 127.0.0.1:8069; }
upstream odoochat  { server 127.0.0.1:8072; }

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name ${DOMAIN};
    location / { return 301 https://\$host\$request_uri; }
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # certs get filled in by certbot; self-signed placeholder until then
    ssl_certificate     /etc/nginx/ssl/${DOMAIN}.crt;
    ssl_certificate_key /etc/nginx/ssl/${DOMAIN}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    # security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # gzip
    gzip on;
    gzip_types text/css text/plain text/xml application/xml application/json application/javascript;

    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;

    # websocket (Odoo live chat / bus)
    location /websocket {
        proxy_pass http://odoochat;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
    location /longpolling { proxy_pass http://odoochat; }

    # cache static assets
    location ~* /web/static/ {
        proxy_cache_valid 200 90m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
    }

    location / { proxy_pass http://odoo; proxy_redirect off; }
}
EOF

mkdir -p /etc/nginx/ssl
ln -sf /etc/nginx/sites-available/odoo.conf /etc/nginx/sites-enabled/odoo.conf
rm -f /etc/nginx/sites-enabled/default

if [[ "${TLS_MODE}" == "cloudflare_origin" ]]; then
  # install the Cloudflare Origin certificate uploaded by 04-harden-and-tune.sh
  log "Installing Cloudflare Origin certificate for ${DOMAIN}"
  [[ -s /tmp/cf-origin.pem && -s /tmp/cf-origin.key ]] || { echo "[harden] FATAL: /tmp/cf-origin.{pem,key} missing"; exit 1; }
  install -m644 /tmp/cf-origin.pem "/etc/nginx/ssl/${DOMAIN}.crt"
  install -m600 /tmp/cf-origin.key "/etc/nginx/ssl/${DOMAIN}.key"
  if ! nginx -t; then echo "[harden] FATAL: nginx config test failed"; exit 1; fi
  systemctl enable --now nginx && systemctl restart nginx
  log "Origin cert installed; nginx serving HTTPS (validated by Cloudflare Full-strict)"
else
  # self-signed placeholder so nginx can start before certbot runs
  if [[ ! -f "/etc/nginx/ssl/${DOMAIN}.crt" ]]; then
    openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
      -keyout "/etc/nginx/ssl/${DOMAIN}.key" \
      -out    "/etc/nginx/ssl/${DOMAIN}.crt" \
      -subj "/CN=${DOMAIN}" >/dev/null 2>&1
  fi
  if ! nginx -t; then echo "[harden] FATAL: nginx config test failed"; exit 1; fi
  systemctl enable --now nginx && systemctl restart nginx
  log "Requesting Let's Encrypt certificate for ${DOMAIN}"
  if certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos \
       -m "${LETSENCRYPT_EMAIL}" --redirect >/tmp/certbot.log 2>&1; then
    log "Let's Encrypt certificate installed"
  else
    log "WARN: certbot failed (see /tmp/certbot.log) - staying on self-signed cert for now"
  fi
  systemctl reload nginx || true
fi

# -----------------------------------------------------------------------------
# 4. Firewall (UFW) - defense in depth on top of the AWS security group
# -----------------------------------------------------------------------------
if [[ "${ENABLE_UFW}" == "true" ]]; then
  log "Configuring UFW"
  apt-get -o DPkg::Lock::Timeout=300 install -y -qq ufw >/dev/null
  ufw --force reset >/dev/null
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  ufw allow OpenSSH >/dev/null
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
  ufw --force enable >/dev/null
  log "UFW enabled (22/80/443)"
fi

# -----------------------------------------------------------------------------
# 5. fail2ban
# -----------------------------------------------------------------------------
if [[ "${ENABLE_FAIL2BAN}" == "true" ]]; then
  log "Configuring fail2ban"
  apt-get -o DPkg::Lock::Timeout=300 install -y -qq fail2ban >/dev/null
  cat > /etc/fail2ban/jail.d/odoo.local <<'EOF'
[sshd]
enabled = true
maxretry = 4
bantime = 1h

[nginx-http-auth]
enabled = true
EOF
  systemctl enable --now fail2ban
  systemctl restart fail2ban
fi

# -----------------------------------------------------------------------------
# 6. unattended-upgrades
# -----------------------------------------------------------------------------
if [[ "${ENABLE_UNATTENDED_UPGRADES}" == "true" ]]; then
  log "Enabling unattended security upgrades"
  apt-get -o DPkg::Lock::Timeout=300 install -y -qq unattended-upgrades >/dev/null
  dpkg-reconfigure -f noninteractive unattended-upgrades >/dev/null 2>&1 || true
fi

# -----------------------------------------------------------------------------
# 7. SSH hardening
# -----------------------------------------------------------------------------
SSHD=/etc/ssh/sshd_config.d/99-hardening.conf
{
  [[ "${SSH_DISABLE_PASSWORD_AUTH}" == "true" ]] && echo "PasswordAuthentication no"
  [[ "${SSH_DISABLE_ROOT_LOGIN}" == "true" ]]    && echo "PermitRootLogin no"
  echo "ChallengeResponseAuthentication no"
  echo "X11Forwarding no"
} > "${SSHD}"
if sshd -t 2>/dev/null; then systemctl reload ssh || systemctl reload sshd || true; log "SSH hardened"; fi

# -----------------------------------------------------------------------------
# 8. CloudWatch agent (only where detailed monitoring is enabled = production)
# -----------------------------------------------------------------------------
if [[ "${MONITORING}" == "enabled" ]]; then
  log "Installing CloudWatch agent (memory + disk metrics)"
  ARCH="$(dpkg --print-architecture)"
  CW="amazon-cloudwatch-agent.deb"
  if wget -q "https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/${ARCH}/latest/amazon-cloudwatch-agent.deb" -O "/tmp/${CW}"; then
    apt-get -o DPkg::Lock::Timeout=300 install -y -qq "/tmp/${CW}" >/dev/null || true
    mkdir -p /opt/aws/amazon-cloudwatch-agent/etc
    cat > /opt/aws/amazon-cloudwatch-agent/etc/config.json <<'EOF'
{
  "agent": {"metrics_collection_interval": 60},
  "metrics": {
    "namespace": "Odoo/Prod",
    "append_dimensions": {"InstanceId": "${aws:InstanceId}"},
    "metrics_collected": {
      "mem":  {"measurement": ["mem_used_percent"]},
      "disk": {"measurement": ["used_percent"], "resources": ["/","/var/lib/odoo"]}
    }
  }
}
EOF
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
      -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json >/dev/null 2>&1 \
      && log "CloudWatch agent running" \
      || log "WARN: CloudWatch agent needs an IAM instance profile with CloudWatchAgentServerPolicy - attach it, then re-run"
    rm -f "/tmp/${CW}"
  fi
fi

# -----------------------------------------------------------------------------
# 9. Nightly backups (DB + filestore) with retention (+ optional S3)
# -----------------------------------------------------------------------------
log "Installing nightly backup job"
install -d -o "${ODOO_USER}" -g "${ODOO_USER}" "${ODOO_HOME}/backups"
cat > /usr/local/bin/odoo-backup.sh <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail
STAMP="\$(date +%Y%m%d-%H%M%S)"
DEST="${ODOO_HOME}/backups"
DB="${TARGET_DBNAME}"
sudo -u postgres pg_dump -Fc "\${DB}" > "\${DEST}/\${DB}-\${STAMP}.dump"
if [[ -d "${ODOO_FILESTORE}/\${DB}" ]]; then
  tar czf "\${DEST}/\${DB}-filestore-\${STAMP}.tar.gz" -C "${ODOO_FILESTORE}" "\${DB}"
fi
# retention
find "\${DEST}" -type f -mtime +${BACKUP_RETENTION_DAYS} -delete
# optional off-box copy
if [[ -n "${BACKUP_S3_BUCKET}" ]]; then
  aws s3 sync "\${DEST}/" "s3://${BACKUP_S3_BUCKET}/${ODOO_ENV}/" --region "${AWS_REGION}" --only-show-errors || true
fi
EOF
chmod +x /usr/local/bin/odoo-backup.sh

cat > /etc/systemd/system/odoo-backup.service <<'EOF'
[Unit]
Description=Odoo nightly backup
[Service]
Type=oneshot
ExecStart=/usr/local/bin/odoo-backup.sh
EOF
cat > /etc/systemd/system/odoo-backup.timer <<'EOF'
[Unit]
Description=Run Odoo backup nightly
[Timer]
OnCalendar=*-*-* 02:30:00
Persistent=true
[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now odoo-backup.timer
log "Nightly backup timer enabled (02:30, ${BACKUP_RETENTION_DAYS}d retention)"

log "Hardening complete for ${ODOO_ENV}"
